### ISSUE TITLE
Argus: NodeSelector and Tolerations not being passed into Collector

### ISSUE THREAD

**Issue by DanMHammer** [logicmonitor/k8s-helm-charts#101]
## Issue

We're using the latest version of the logicmonitor/argus and logicmonitor/collectorset-controller charts. While deploying logicmonitor/argus, we're passing in a `nodeSelector` and `tolerations` to the `statefulsetspec` for the collector, and it's not applying to the collector.

### Action

Example taint on the nodes: `key1=value1:NoSchedule`
Example label on the nodes: `label1=""`

Run:
```
     helm upgrade \
          --install \
          --debug \
          --wait \
          --cleanup-on-fail \
          --namespace="default" \
          --set accessID=<<accessId>> \
          --set accessKey=<<accessKey>> \
          --set account=<<account>> \
          --set nodeSelector.label1="" \
          --set tolerations[0].key=key1 \
          --set tolerations[0].operator="Exists" \
          --set tolerations[0].effect="NoSchedule" \
          --set enableRBAC=true \
          --set clusterName=cluster1 \
          collectorset-controller logicmonitor/collectorset-controller

    helm upgrade \
          --install \
          --debug \
          --wait \
          --cleanup-on-fail \
          --namespace="default" \
          --set accessID=<<accessId>> \
          --set nodeSelector.label1="" \
          --set tolerations[0].key="key1" \
          --set tolerations[0].operator="Exists" \
          --set tolerations[0].effect="NoSchedule" \
          --set accessKey=<<accessKey>> \
          --set account=<<account>> \
          --set enableRBAC=true \
          --set clusterName=cluster1 \
          --set clusterGroupID=<<clusterGroupID>> \
          --set collector.groupID=<<collectorGroup>> \
          --set collector.replicas=1 \
          --set collector.size=small \
          --set collector.escalationChainID=25 \
          --set collector.statefulsetspec.template.spec.nodeSelector.label1="" \
          --set collector.statefulsetspec.template.spec.tolerations[0].key="key1" \
          --set collector.statefulsetspec.template.spec.tolerations[0].operator="Exists" \
          --set collector.statefulsetspec.template.spec.tolerations[0].effect="NoSchedule" \
          argus logicmonitor/argus
```

### Expected Behavior

The following resources are created

On pods with label1 and taint key1=value1:NoSchedule:

* pod/argus-xxxx
* pod/collectorset-controller-xxxx
* Collector Pod: pod/cluster1-0
* service/argus
* service/collectorset-controller
* deployment.apps/argus
* deployment.apps/collectorset-controller
* replicaset.apps/argus
* replicaset.apps/collectorset-controller
* Collector statefulset: statefulset.apps/cluster1

On pods other Pods:
N/A

### Actual Behavior

The following resources are created

On pods with label1 and taint key1=value1:NoSchedule:

* pod/argus-xxxx
* pod/collectorset-controller-xxxx
* service/argus
* service/collectorset-controller
* deployment.apps/argus
* deployment.apps/collectorset-controller
* replicaset.apps/argus
* replicaset.apps/collectorset-controller

On pods other Pods:
* Collector Pod: pod/cluster1-0
* Collector statefulset: statefulset.apps/cluster1

### Details
The nodeselector is being rendered into the template and is clearly there in the output of `--dry-run`

```
apiVersion: logicmonitor.com/v1alpha1
kind: CollectorSet
metadata:
  name: cluster1
  namespace: default
spec:
  clusterName: cluster1
  escalationChainID: 25
  groupID: 4
  imagePullPolicy: Always
  imageRepository: logicmonitor/collector
  imageTag: latest
  policy:
    distributionStrategy: RoundRobin
    orchestrator: Kubernetes
  replicas: 1
  size: small
  statefulsetspec:
    template:
      spec:
        nodeSelector:
          label1: ""
        tolerations:
        - effect: NoSchedule
          key: key1
          operator: Exists
```

It appears that the nodeSelector and tolerations are not being passed to the collector pod upon execution

From `kubectl describe pod customer1-0`:

```
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                                     node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
```
